server:
  port: 9002 # 后期该微服务多实例，端⼝从9002递增（10个以内）
spring:
  application:
    name: lagou-gateway
  cloud:
    gateway:
      routes:
        - id: service-user
#          uri: http://127.0.0.1:8090
          uri: lb://lagou-service-user
          predicates:
            - Path=/api/user/**
        - id: service-email
          #          uri: http://127.0.0.1:8090
          uri: lb://lagou-service-email
          predicates:
            - Path=/api/email/**
        - id: service-code
          #          uri: http://127.0.0.1:8090
          uri: lb://lagou-service-code
          predicates:
            - Path=/api/code/**
eureka:
  client:
    serviceUrl: # eureka server的路径
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/ #把 eureka 集群中的所有 url 都填写了进来，也可以只写⼀台，因为各个eureka server 可以同步注册表
  instance: #使⽤ip注册，否则会使⽤主机名注册了（此处考虑到对⽼版本的兼容，新版本经过实验都是ip）
    prefer-ip-address: true #⾃定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
    instance-id:  ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
management:
  endpoints:
    web:
      exposure:
        include: "*"

ip:
  limit:
    minutes: 3
    maxTimes: 6